/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FeakinDrawio {
        "file": string;
    }
}
declare global {
    interface HTMLFeakinDrawioElement extends Components.FeakinDrawio, HTMLStencilElement {
    }
    var HTMLFeakinDrawioElement: {
        prototype: HTMLFeakinDrawioElement;
        new (): HTMLFeakinDrawioElement;
    };
    interface HTMLElementTagNameMap {
        "feakin-drawio": HTMLFeakinDrawioElement;
    }
}
declare namespace LocalJSX {
    interface FeakinDrawio {
        "file"?: string;
    }
    interface IntrinsicElements {
        "feakin-drawio": FeakinDrawio;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "feakin-drawio": LocalJSX.FeakinDrawio & JSXBase.HTMLAttributes<HTMLFeakinDrawioElement>;
        }
    }
}
